title: "Jacky 博客"
description: "Jacky 静态网站生成器演示"
author: "你的名字"
url: "http://127.0.0.1:8080"
source: "."
destination: "_site"
layouts_dir: "_layouts"
data_dir: "_data"
includes_dir: "_includes"
posts_dir: "_posts"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: "date"
paginate: 10
paginate_path: "page" 